name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
jobs:
    deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
        - name: Checkout
        uses: actions/checkout@v2
        - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: 'azureuser'
            server: 'scfdev.oracle.idfcfirst.veefin.in'
            ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
            local_path: './static/*'
            remote_path: '/var/www/app'
            sftpArgs: '-o ConnectTimeout=5'
    #   run: composer run-script test
